In [100]:
import pandas as pd
import numpy as np

In [101]:
url = r'C:\Users\PC\Desktop\Projetos\Python\Projeto IPCA\tabela7060_2023_2024.xlsx'

dados = pd.read_excel(url, skiprows=2, nrows=4512)

In [102]:
dados.tail()

,Mês,"Geral, grupo, subgrupo, item e subitem",Rio Branco (AC),São Luís (MA),Aracaju (SE),Campo Grande (MS),Goiânia (GO),Brasília (DF),RM de Belém (PA),RM de Fortaleza (CE),RM de Recife (PE),RM de Salvador (BA),RM de Belo Horizonte (MG),RM da Grande Vitória (ES),RM do Rio de Janeiro (RJ),RM de São Paulo (SP),RM de Curitiba (PR),RM de Porto Alegre (RS)
4507,dezembro 2024,1201048.Cerveja,0,0,0.04,0.62,-0.11,-0.18,-0.47,1.03,0.54,0.1,-1.42,-0.22,0.7,0.53,1.01,0.82
4508,dezembro 2024,1201051.Outras bebidas alcoólicas,-,1.91,-,1.83,-,-,-,-,0.7,-,-,-0.17,-,-,-,-
4509,dezembro 2024,1201052.Vinho,-,-,-,-,-,-,-,-,-,-,-,-,3.87,-,-,-
4510,dezembro 2024,1201061.Doces,-,-,0.51,-,0.83,-,-,-,-,-,-,-,-,-,-,-
4511,dezembro 2024,1201088.Sorvete,0.18,-,1.02,0.95,2.45,-,-,0.5,-,0.5,-,-,-,0.95,1.61,-

# Tratamentos

    - alterar nome das colunas:
        - 'Geral, grupo, subgrupo, item e subitem' para Items
        - Coluna de estados apenas para siglas
        - Meses para apenas meses do ano
    - tratar nomes de dados:
        - coluna de items para apenas os nomes, sem numeros
    - tratar valores:
        - trocar vazios para 0.0
        - mudar para float64

In [103]:
# tratando nome de colunas
dados = dados.rename(columns={
       'Geral, grupo, subgrupo, item e subitem': 'Itens', 
       'Rio Branco (AC)' : 'AC',
       'São Luís (MA)':'MA', 
       'Aracaju (SE)':'SE',
       'Campo Grande (MS)':'MS', 
       'Goiânia (GO)':'GO', 
       'Brasília (DF)':'DF',
       'RM de Belém (PA)': 'PA',
       'RM de Fortaleza (CE)' : 'CE',
       'RM de Recife (PE)' : 'PE',
       'RM de Salvador (BA)' : 'BA',
       'RM de Belo Horizonte (MG)' : 'MG',
       'RM da Grande Vitória (ES)' : 'ES',
       'RM do Rio de Janeiro (RJ)' : 'RJ',
       'RM de São Paulo (SP)' : 'SP', 
       'RM de Curitiba (PR)' : 'PR',
       'RM de Porto Alegre (RS)' : 'RS'                
                              })

In [104]:
# tratando coluna de itens
# ^: indica o início da string.
# \d+: corresponde a um ou mais dígitos.
dados['Itens'] = dados['Itens'].str.replace('^\d+\.', '', regex=True)

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
C:\Users\PC\AppData\Local\Temp\ipykernel_15972\2871686057.py:4: SyntaxWarning: invalid escape sequence '\d'
  dados['Itens'] = dados['Itens'].str.replace('^\d+\.', '', regex=True)

In [105]:
# tratando valores nulos e alterando tipo para format
col_numericas = list(dados.columns)

dados[col_numericas[2:]] = dados[col_numericas[2:]].apply(lambda x: x.replace('-', '0.0')).astype(np.float64)

In [106]:
# preciso excluir os dados que podem poluir a analise, ex.:Alimentação e bebidas que é a media desse grupo ou Cereais, leguminosas e oleaginosas
dados['Itens'].unique().tolist()

exclusao = [
'Alimentação e bebidas',
'Cereais, leguminosas e oleaginosas',
'Farinhas, féculas e massas',
'Açúcares e derivados',
'Hortaliças e verduras',
'Frutas',
'Carnes',
'Pescados',
'Carnes e peixes industrializados', 
'Aves e ovos',
'Leites e derivados',
'Panificados',
'Óleos e gorduras',
'Bebidas e infusões',
'Enlatados e conservas',
'Sal e condimentos',
'Alimentação fora do domicílio'
]

df = dados.query('Itens not in @exclusao')

In [107]:
# alterar tipo de meses

list(dados['Mês'].unique())

meses_conversao = {
 'janeiro 2023'   : '2023-01'  ,
 'fevereiro 2023' : '2023-02'  ,
 'março 2023'     : '2023-03'  ,
 'abril 2023'     : '2023-04'  ,
 'maio 2023'      : '2023-05'  ,
 'junho 2023'     : '2023-06'  ,
 'julho 2023'     : '2023-07'  ,
 'agosto 2023'    : '2023-08'  ,
 'setembro 2023'  : '2023-09'  ,
 'outubro 2023'   : '2023-10'  ,
 'novembro 2023'  : '2023-11'  ,
 'dezembro 2023'  : '2023-12'  ,
 'janeiro 2024'   : '2024-01' ,
 'fevereiro 2024' : '2024-02' ,
 'março 2024'     : '2024-03' ,
 'abril 2024'     : '2024-04' ,
 'maio 2024'      : '2024-05' ,
 'junho 2024'     : '2024-06' ,
 'julho 2024'     : '2024-07' ,
 'agosto 2024'    : '2024-08' ,
 'setembro 2024'  : '2024-09' ,
 'outubro 2024'   : '2024-10' ,
 'novembro 2024'  : '2024-11' ,
 'dezembro 2024'  : '2024-12'
}

df['Mês'] = df['Mês'].replace(meses_conversao) # 
df['Mês'] = pd.to_datetime(df['Mês'], format='%Y-%m')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4080 entries, 1 to 4511
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Mês     4080 non-null   datetime64[ns]
 1   Itens   4080 non-null   object
 2   AC      4080 non-null   float64
 3   MA      4080 non-null   float64
 4   SE      4080 non-null   float64
 5   MS      4080 non-null   float64
 6   GO      4080 non-null   float64
 7   DF      4080 non-null   float64
 8   PA      4080 non-null   float64
 9   CE      4080 non-null   float64
 10  PE      4080 non-null   float64
 11  BA      4080 non-null   float64
 12  MG      4080 non-null   float64
 13  ES      4080 non-null   float64
 14  RJ      4080 non-null   float64
 15  SP      4080 non-null   float64
 16  PR      4080 non-null   float64
 17  RS      4080 non-null   float64
dtypes: datetime64[ns](1), float64(16), object(1)
memory usage: 605.6+ KB

C:\Users\PC\AppData\Local\Temp\ipykernel_15972\1882563749.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Mês'] = df['Mês'].replace(meses_conversao) #
C:\Users\PC\AppData\Local\Temp\ipykernel_15972\1882563749.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Mês'] = pd.to_datetime(df['Mês'], format='%Y-%m')

# Lista de Itens
 - criar uma lista com itens de uma cesta e avalia-los

In [108]:
categorias = {

    'graos' :           ['Arroz', 'Feijão - carioca (rajado)', 'Farinha de mandioca', 'Farinha de trigo', 'Macarrão'],
    'hortalicas' :      ['Batata-inglesa', 'Tomate', 'Cebola', 'Alface', 'Cenoura', 'Couve', 'Pimentão'],
    'frutas' :          ['Banana - prata', 'Maçã', 'Laranja - pera', 'Mamão', 'Melancia'],
    'proteinas' :       ['Acém', 'Costela', 'Contrafilé', 'Alcatra', 'Carne de porco', 'Frango inteiro', 'Frango em pedaços', 'Ovo de galinha'], 
    'laticinios' :      ['Leite longa vida', 'Queijo', 'Iogurte e bebidas lácteas'],
    'oleos_gorduras' :  ['Manteiga', 'Margarina', 'Óleo de soja', 'Azeite de oliva'],
    'outros' :          ['Café moído', 'Café solúvel', 'Sal']

}

# caso eu queira visualizar o que tem em cada item
# for categoria, itens in categorias.items():
#     print(f'cagoria:{categoria}')
#     for item in itens:
#         print(f' - {item}')

# iteração de cada item (invertendo os valores do dicionario)
item_categoria = {item : categoria for categoria, itens in categorias.items() for item in itens}

In [140]:
# Filtrar apenas SP
ipca_sp = df[['Mês', 'Itens', 'SP']]

# filtrar apenas os itens presentes nas categorias
ipca_sp = ipca_sp[ipca_sp['Itens'].isin(item_categoria)]
ipca_sp = ipca_sp.reset_index(drop=True)

# transformar em long
ipca_sp_pivot = ipca_sp.pivot_table(
    index='Mês',
    columns='Itens',
    values='SP'
)

# incluir coluna total para linha
ipca_sp_pivot['Total_mensal'] = ipca_sp_pivot.sum(axis=1)

# incluir linha total para cada ano
total_ano = ipca_sp_pivot.groupby(ipca_sp_pivot.index.year).sum()
ipca_sp_pivot = ipca_sp_pivot = pd.concat([ipca_sp_pivot, total_ano])


# verificar qual item teve o maior impacto no indice
ipca_sp_pivot['Alimento_maior_inflacao'] = ipca_sp_pivot.drop(columns='Total_mensal').idxmax(axis=1)
ipca_sp_pivot['Alimento_menor_inflacao'] = ipca_sp_pivot.drop(columns=['Total_mensal', 'Alimento_maior_inflacao']).idxmin(axis=1)

ipca_sp_pivot

Itens,Acém,Alcatra,Alface,Arroz,Azeite de oliva,Banana - prata,Batata-inglesa,Café moído,Café solúvel,Carne de porco,...,Melancia,Ovo de galinha,Pimentão,Queijo,Sal,Tomate,Óleo de soja,Total_mensal,Alimento_maior_inflacao,Alimento_menor_inflacao
Mês,,,,,,,,,,,,,,,,,,,,,
2023-01-01 00:00:00,-2.45,-1.78,11.38,2.44,1.19,2.83,12.40,0.08,0.0,-2.99,...,0.0,2.88,-5.15,0.27,0.0,0.95,-0.26,56.24,Batata-inglesa,Cebola
2023-02-01 00:00:00,-3.05,-2.59,9.64,1.11,-0.25,3.54,-7.72,-0.84,0.0,1.42,...,0.0,0.52,-7.79,3.46,0.0,-14.91,-3.66,26.57,Cenoura,Tomate
2023-03-01 00:00:00,1.10,-1.87,7.24,1.20,2.13,0.54,-12.73,-2.31,0.0,-0.34,...,0.0,6.37,1.76,-2.34,0.0,0.48,-2.59,26.42,Cenoura,Batata-inglesa
2023-04-01 00:00:00,-1.79,-2.82,0.69,-0.69,0.54,-6.64,2.67,0.17,0.0,1.77,...,0.0,2.69,18.68,3.31,0.0,15.64,-4.06,26.70,Pimentão,Banana - prata
2023-05-01 00:00:00,-1.90,0.92,-2.03,1.47,1.81,0.04,0.18,-0.07,0.0,-0.84,...,0.0,0.23,-4.20,2.66,0.0,5.21,-5.44,-22.95,Tomate,Mamão
2023-06-01 00:00:00,1.80,0.02,-5.34,-0.63,-0.44,-4.62,5.10,0.72,0.0,-3.59,...,0.0,1.97,-0.79,-1.77,0.0,-2.44,-8.95,-43.94,Batata-inglesa,Óleo de soja
2023-07-01 00:00:00,-3.65,-5.36,1.02,-0.92,4.11,4.75,-2.95,-2.06,0.0,-1.80,...,0.0,0.19,2.51,1.64,0.0,-4.24,-6.58,-31.12,Banana - prata,Feijão - carioca (rajado)
2023-08-01 00:00:00,-0.21,-4.52,-4.46,2.08,2.39,2.95,-14.45,-2.71,0.0,-0.26,...,0.0,-3.42,-4.74,2.28,0.0,-8.89,-2.07,-77.25,Banana - prata,Batata-inglesa
2023-09-01 00:00:00,-4.52,1.23,-5.15,2.75,4.96,-4.19,-2.49,-1.09,0.0,-0.67,...,0.0,-1.99,1.13,-2.08,0.0,3.95,-3.02,-64.02,Maçã,Cenoura
2023-10-01 00:00:00,-0.39,-0.69,6.40,3.49,6.44,2.31,3.78,-1.08,0.0,1.08,...,0.0,-3.93,1.43,-0.46,0.0,2.75,0.05,47.01,Cebola,Leite longa vida
2023-11-01 00:00:00,2.61,2.41,11.39,3.05,5.20,0.72,9.52,0.74,0.0,-0.43,...,0.0,1.04,-0.56,1.43,0.0,-3.56,-0.77,42.55,Cebola,Mamão
2023-12-01 00:00:00,-0.83,1.20,0.45,5.97,3.47,5.64,16.63,-0.06,0.0,2.66,...,0.0,1.50,2.44,-2.12,0.0,8.88,3.13,88.11,Batata-inglesa,Queijo
2024-01-01 00:00:00,-2.02,0.33,-1.09,4.63,3.56,4.91,22.34,0.60,0.0,-2.90,...,0.0,-4.57,0.18,2.84,0.0,-5.47,3.45,70.70,Cenoura,Mamão
2024-02-01 00:00:00,0.66,1.46,4.74,4.36,2.23,7.34,8.78,-1.82,0.0,0.14,...,0.0,1.27,-11.24,-1.12,0.0,6.55,-0.50,60.34,Cenoura,Pimentão
2024-03-01 00:00:00,1.59,-4.58,3.27,1.24,4.38,6.93,-5.00,1.33,0.0,-2.72,...,0.0,3.23,11.63,-3.68,0.0,5.88,0.14,57.86,Cebola,Cenoura
2024-04-01 00:00:00,0.97,0.88,2.49,-2.05,1.34,-0.31,-7.61,2.94,0.0,2.43,...,0.0,1.60,25.26,-0.57,0.0,19.41,-0.02,81.75,Mamão,Batata-inglesa
2024-05-01 00:00:00,-1.14,-0.77,-1.46,0.75,2.92,-7.31,12.15,2.69,0.0,-0.59,...,0.0,-1.77,-4.76,-2.00,0.0,-10.55,0.15,9.48,Cebola,Tomate
2024-06-01 00:00:00,-1.06,-1.09,-5.18,2.18,1.43,-5.50,17.67,2.46,0.0,1.37,...,0.0,1.16,-5.93,1.28,0.0,13.15,0.17,-15.16,Batata-inglesa,Mamão
2024-07-01 00:00:00,-0.85,-0.98,-3.04,-0.02,0.64,-1.30,-6.42,2.73,0.0,1.14,...,0.0,-2.11,-10.41,-1.86,0.0,-29.94,0.26,-112.55,Café moído,Tomate
2024-08-01 00:00:00,0.40,1.69,-6.98,-1.40,2.06,1.87,-17.70,2.97,0.0,3.68,...,0.0,-2.55,-1.08,1.71,0.0,-16.89,1.58,-28.09,Mamão,Batata-inglesa
2024-09-01 00:00:00,2.97,4.38,-1.36,-0.02,1.28,6.96,-6.77,1.03,0.0,5.48,...,0.0,-2.54,-5.32,0.51,0.0,-3.11,2.54,31.80,Mamão,Cebola
2024-10-01 00:00:00,11.43,5.00,-2.31,-0.23,-0.30,-7.71,0.22,4.64,0.0,0.20,...,0.0,-0.91,4.64,0.94,0.0,8.78,4.51,17.49,Acém,Mamão
2024-11-01 00:00:00,6.93,9.62,9.33,-0.04,0.29,0.64,0.47,3.78,0.0,6.28,...,0.0,0.82,0.87,1.19,0.0,-1.48,11.50,92.17,Óleo de soja,Leite longa vida
2024-12-01 00:00:00,8.36,9.98,5.78,-0.73,0.63,5.53,-11.61,5.49,0.0,4.48,...,0.0,-0.08,-12.14,1.82,0.0,-5.84,6.30,32.84,Alcatra,Pimentão
2023,-13.28,-13.85,31.23,21.32,31.55,7.87,9.94,-8.51,0.0,-3.99,...,0.0,8.05,4.72,6.28,0.0,3.82,-34.22,74.32,Azeite de oliva,Óleo de soja
2024,28.24,25.92,4.19,8.67,20.46,12.05,6.52,28.84,0.0,18.99,...,0.0,-6.45,-8.30,1.06,0.0,-19.51,30.08,298.63,Laranja - pera,Tomate